articles/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = "articles"

urlpatterns = [
    path('', views.articles_view, name='articles'),
    path('creer/', views.creer_view, name ='creer'),
    path('<slug:slug>/', views.article_view, name='article')
   
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('contact/', views.contact_view, name='contact'),
    path('remerciement/' , views.remerciements_view ,name='remerciements'),
    path('articles/', include('articles.urls' ), name='articles'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

class Article(models.Model):
    titre = models.CharField(max_length=150)
    contenu =models.TextField()
    slug =models.SlugField(max_length=100)
    date_publication = models.DateField(auto_now_add=True)
    image = models.ImageField(default='default.jpg')

    def __str__(self):
        return self.titre

articles/forms.py
from django.forms import ModelForm
from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['titre', 'contenu', 'slug', 'image']

blog/forms.py
from django import forms

class ContactForm(forms.Form):
    nom = forms.CharField(max_length=200)
    prenom =forms.CharField(max_length=200)
    email =forms.EmailField()
    message =forms.CharField(widget=forms.Textarea)

articles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404,HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse  

from .forms import ArticleForm

from .models import Article

def articles_view(request):
    articles = Article.objects.all().order_by('-date_publication')
    return render(request, 'articles/list.html', context={'articles': articles})

def article_view(request, slug):
    article = get_object_or_404(Article,slug=slug)
    return render(request, 'articles/detail.html', context={"article": article})










    # try:
    #  article = Article.objects.get(slug=slug)
   
    #  return render(request, 'articles/detail.html', context={"article": article})
    # except Article.DoesNotExist:
    #    raise  Http404("L'article nexiste pas")


def creer_view(request):
    form  =ArticleForm()
    if request.method == 'POST':
        form=ArticleForm(request.POST ,request.FILES) # on recupere ce qui est entre dans notre methode post
        form.save()
        return HttpResponseRedirect(reverse('articles:articles')) # une fois les donner sauvegarder redirige lutilisateur sur la page article
    return render(request,'articles/creer.html', context ={'form':form} )

blog/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from  .forms import ContactForm
from django.urls import reverse
from django.core.mail import send_mail



def home_view(request):
    # return HttpResponse('Hello World!')
    return render(request, 'home.html')

def contact_view(request):
    # return HttpResponse('Contactez nous')
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)                                      # la on recupere les imformation qui sont envoyer avec le parametre qui recupere toutes les informations en question
        if form.is_valid():    # la on recupere le nom
            nom =form.cleaned_data['nom']
            prenom =form.cleaned_data['prenom'] 
            email =form.cleaned_data['email']
            message =form.cleaned_data['message']
           
            titre = f'blog |  {nom} {prenom} {email}'
            send_mail(titre, message, 'blog.maxadj@gmail.com', ['blog.maxadj@gmail.com',])


        return HttpResponseRedirect(reverse('remerciements'))                  # ici une fois les information entrer on doit avoir une page de remerciement 
    return render(request, 'contact.html', {"form":form})


def remerciements_view(request):
    return HttpResponse("merci de nous avoir contacter")


articles/templates/articles/creer.html
{% extends 'template_base.html' %}

{% block contenu %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <h1>Nouvel Article</h1>
            <hr class="my-4">
            <form action="{% url 'articles:creer' %}" method="POST" enctype="multipart/form-data">
                {%csrf_token%}
                {{form}}
                <button type="submit" class="btn btn-danger">Creer</button>
            </form>
        </div>
    </div>

</div>



{% endblock %}

articles/templates/articles/detail.html
{% extends 'template_base.html' %}

{% block contenu %}
<div class="container">
    <h1>{{ article.titre }}</h1>
    <img src="{{article.image.url}}" alt="{{ article.titre }}">
    <p>{{ article.contenu }}</p>
    <span>{{ article.date_publication }}</span>
</div>
{% endblock %}

articles/templates/articles/list.html
{% extends 'template_base.html' %}

{% block titre %}Page d'articles{% endblock%}

{% block contenu %}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-11">
            <h1>Liste d'articles</h1>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{% url 'articles:creer'%}">
                Creer
            </a>
        </div>
    </div>
</div>

<hr class="my-4">

<div class="container">
    <div class="row">
        {% for article in articles %}
        <div class="col-med-6 col-lg-4 mb-4">
            <div class="card">
                <a href="{% url 'articles:article' slug=article.slug %}">
                    <img class="card-img-top" src="{{article.image.url}}" alt="{{ article.titre }}">
                </a>
                <div class="card-body">
                    <h2 class="card-title">{{ article.titre }}</h2>
                    <p class="class-text">{{ article.contenu }}</p>
                    <p class="card-text">
                        <small class="card-text">
                            {{ article.date_publication }}
                        </small>
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'template_base.html'%}

{%block titre%} Page de Contact {%endblock%}

{%block contenu%}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 mt-4">
            <h1>Contactez-nous</h1>
            <hr class="my-4">
            <form action="{% url 'contact' %}" method="POST">
                {%csrf_token%}
                {{form}}
                <button type="submit" class="btn btn-danger">Envoyer</button>
            </form>
        </div>
    </div>
</div>


{%endblock%}

templates/home.html
{%  extends 'template_base.html' %}
{% load static %}

{% block titre %}Page d'accueil{% endblock%}

{% block contenu %}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
        <h1 class="display-4">Voyages</h1>
        <p class="lead text-muted">
            Voyager c'est ma vie! Je vais vous faire découvrir mes destinations
            favorites à travers ce blog.
        </p>
        <a href="{% url 'articles:articles' %}" type="button" class="btn btn-primary">
            Articles
        </a>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg mb-4">
            <img class="w-100" src="{% get_media_prefix %}voyages.jpg" alt="Image de blog">
        </div>
        <div class="col-lg text-justify">
            <h2>Mes Aventures</h2>
            <hr class="my-4">
            <p class="lead">
                Bienvenue sur mon blog de voyage.
                Chaque année, je découvre une nouvelle ville en recherche
                de délices culinaires et d'aventures. A travers ce blog,
                je partage ma passion pour l'exploration et vous fait découvrir
                des villes du monde dans toute leur splendeur.
            </p>
        </div>
    </div>
    <hr class="my-4">
    <div class="row">
        <div class="col-lg-4 text-center">
            <span class="fa-stack fa-5x">
                <i class="fas fa-circle fa-stack-2x fa-inverse"></i>
                <i class="fas fa-hiking fa-stack-1x"></i>
            </span>
            <h2 class="display-6">Randonnée</h2>
            <p>
                A pieds, c'est encore mieux! Explorer des endroits
                où très peu de personnes n'osent s'aventurer.
            </p>
        </div>
        <div class="col-lg-4 text-center">
            <span class="fa-stack fa-5x">
                <i class="fas fa-circle fa-stack-2x fa-inverse"></i>
                <i class="fas fa-utensils fa-stack-1x"></i>
            </span>
            <h2 class="display-6">Dégustation</h2>
            <p>
                Aller à la découverte de nouvelles saveures. 
                Des menus en couleur et épicés par des saveures à couper le souffle.
            </p>
        </div>

       

        <div class="col-lg-4 text-center">
            <span class="fa-stack fa-5x">
                <i class="fas fa-circle fa-stack-2x fa-inverse"></i>
                <i class="fas fa-route fa-stack-1x"></i>
            </span>
            <h2 class="display-6">Découverte</h2>
            <p>
                Des falaises, des caves, 
                des plages à sable blanc s'étendant sur des kilomètres.
            </p>
        </div>
    </div>
</div>

{% endblock %}


templates/template_base.html
{%load static %}

<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titre %}{% endblock%}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/styles.css '%}">
</head>

<body>
    <!-- <ul style="list-style: none">
        <li style="display: inline-block; padding: 10px 20px;">
            
            <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li style="display: inline-block; padding: 10px 20px;">
            <a href="{% url 'articles:articles' %}">Articles</a>
        </li>
        <li style="display: inline-block; padding: 10px 20px;">
            <a href="{% url 'contact' %}">Contact</a>
        </li>
    </ul> -->
    <!-- 
    <div class="container">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'home' %}">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:articles' %}">Articles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
        </ul>
    </div> -->




    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'logo_nav.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'home' %}">ACCUEIL</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'articles:articles' %}">ARTICLES</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact' %}">CONTACT</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block contenu %} {% endblock %}

    <footer class="bg-secondary white text-white mt-5 pt-2 pb-5">
        <div class="container">
            <span>&copy; 2020 | vblog.com </span>
            
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>

</html>